---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: sigma-dai-api
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: sigma-dai-api
    group: sigma-dai
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
spec:
  entryPoints:
    - web
    - web-secure
  routes:
    - kind: Rule
      match: PathPrefix(`/api/ssai`)
      middlewares:
        - name: multi-tenancies
          namespace: sigma-auth
        - name: sigma-dai-api-cors
      services:
        - kind: Service
          name: sigma-dai-api
          port: 80
          strategy: RoundRobin
