apiVersion: v1
data:
  micro.conf: |+
    {{ tpl (.Files.Get "config/micro.conf") . | nindent 4 }}
kind: ConfigMap
metadata:
  name: sigma-dai-cms-conf
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: sigma-dai-cms
    group: sigma-dai
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}