# Strip prefix /authentication
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: sigma-dai-cms
    group: sigma-dai
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  name: sigma-dai-cms-strip-prefix
spec:
  stripPrefix:
    prefixes:
      - /micro/cms/ssai
    forceSlash: false

---

# cors header
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: sigma-dai-cms
    group: sigma-dai
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  name: sigma-dai-cms-cors
spec:
  headers:
    accessControlAllowHeaders: 
      - "*"
    accessControlAllowMethods:
      - "GET"
      - "POST"
      - "OPTIONS"
      - "PATCH"
      - "PUT"
      - "DELETE"
    accessControlAllowOriginList: 
      - "*"
    accessControlMaxAge: 100
    addVaryHeader: true