apiVersion: v1
kind: Service
metadata:
  name: sigma-dai-cms
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: sigma-dai-cms
    group: sigma-dai
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
spec:
  type: ClusterIP
  ports:
  - name: rest
    port: 80
    targetPort: 80
    protocol: TCP 
  selector:
    app: sigma-dai-cms
    group: sigma-dai
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
