apiVersion: v1
data:
  default.yaml: |+
    {{ tpl (.Files.Get "config/default.yaml") . | nindent 6 }}
kind: ConfigMap
metadata:
  labels:
    app: sigma-interactive-api
    group: sigma-interactive
  name: sigma-interactive-api-config
  namespace: sigma-interactive
