apiVersion: apps/v1
kind: Deployment
metadata:
  name: sigma-interactive-api
  labels:
    app: sigma-interactive-api
    group: sigma-interactive
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: sigma-interactive-api
      group: sigma-interactive
      {{- include "helm-example.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: sigma-interactive-api
        group: sigma-interactive
        {{- include "helm-example.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "helm-example.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: sigma-interactive-api
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: grpc
              containerPort: 50051
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/interactive/v1/health
              port: http
          readinessProbe:
            httpGet:
              path: /api/interactive/v1/health
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
