apiVersion: v1
kind: Service
metadata:
  name: sigma-interactive-api
  labels:
    app: ilp-campaign-service
    group: sigma-interactive
    {{- include "helm-example.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
    - name: grpc
      port: 50051
      protocol: TCP
  selector:
    {{- include "helm-example.selectorLabels" . | nindent 4 }}
