apiVersion: v1
data:
  config.yaml: |+
    {{ tpl (.Files.Get "config/migration.yaml") . | nindent 4 }}
kind: ConfigMap
metadata:
  name: sigma-dai-migration-conf
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: sigma-dai-migration-conf
    group: sigma-dai
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}