apiVersion: v1
data:
  default.yaml: |+
    {{ tpl (.Files.Get "config/api-config.yaml") . | nindent 4 }}
kind: ConfigMap
metadata:
  labels:
    app: sigma-dai-config
    group: sigma-dai
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  name: sigma-dai-config
  namespace: {{ .Release.Namespace | quote }}
